language: node_js

node_js:
  - "lts/*"

cache: false

services:
  - docker

install:
  - "bin/installDeps.sh"
  - "export GIT_HASH=$(git rev-parse --verify --short HEAD)"

#before_script:
#  - "tests/frontend/travis/sauce_tunnel.sh"

script:
  - "tests/frontend/travis/runner.sh"

env:
  global:
    - secure: "WMGxFkOeTTlhWB+ChMucRtIqVmMbwzYdNHuHQjKCcj8HBEPdZLfCuK/kf4rG\nVLcLQiIsyllqzNhBGVHG1nyqWr0/LTm8JRqSCDDVIhpyzp9KpCJQQJG2Uwjk\n6/HIJJh/wbxsEdLNV2crYU/EiVO3A4Bq0YTHUlbhUqG3mSCr5Ec="
    - secure: "gejXUAHYscbR6Bodw35XexpToqWkv2ifeECsbeEmjaLkYzXmUUNWJGknKSu7\nEUsSfQV8w+hxApr1Z+jNqk9aX3K1I4btL3cwk2trnNI8XRAvu1c1Iv60eerI\nkE82Rsd5lwUaMEh+/HoL8ztFCZamVndoNgX7HWp5J/NRZZMmh4g="

jobs:
  include:
    - name: "Load Testing"
      install:
        - "npm install -g"
        - "git clone https://github.com/ether/etherpad-lite.git etherpad"
        - "cd etherpad"
        - "bin/installDeps.sh"
        - "export GIT_HASH=$(git rev-parse --verify --short HEAD)"
        - "cd src && npm install && cd -"
#        - "cd .."
#        - "cd etherpad"
      script:
        - "tests/frontend/travis/runnerLoadTest.sh"

notifications:
  irc:
    channels:
      - "irc.freenode.org#etherpad-lite-dev"
